### ISSUE TITLE
ldproxy cadastralparcels : get by ID fails

### ISSUE THREAD

**Issue by pduchesne** [opengeospatial/wfs3hackathon#1]
The 'cadastralparcels' feature type in the ldproxy hackathon instance fails on get by ID. 
Try this out : 
http://wfs3hackathon.ldproxy.net/rest/services/nl_cp/cadastralparcel/cadastralparcel.35533?f=json

appears to fail in HTML, too : 
http://wfs3hackathon.ldproxy.net/rest/services/nl_cp/cadastralparcel/cadastralparcel.35533

Other feature types look fine in that respect.

**Comment by cportele** [comment]
Hm, I am pretty sure it was working a few days ago. Now the WFS returns an exception:

```
<ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 https://geodata.nationaalgeoregister.nl/inspire/schemas/ows/1.1.0/owsAll.xsd">
<ows:Exception exceptionCode="NoApplicableCode">
<ows:ExceptionText>
java.lang.IllegalStateException: No FID expression found for type http://inspire.ec.europa.eu/schemas/cp/4.0:CadastralParcel. Did you mean Expression.NIL? No FID expression found for type http://inspire.ec.europa.eu/schemas/cp/4.0:CadastralParcel. Did you mean Expression.NIL?
</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
```

http://wfs3hackathon.ldproxy.net/rest/services/nl_cp/CadastralParcel/cadastralparcel.1/?f=xml

**Comment by cportele** [comment]
It seems to be a (new?) issue in the underlying WFS.

https://geodata.nationaalgeoregister.nl/inspire/ps/wfs?REQUEST=GetFeature&SERVICE=WFS&version=2.0.0&TYPENAMES=ps:ProtectedSite&RESOURCEID=_2

works, but 

https://geodata.nationaalgeoregister.nl/inspire/cp/wfs?REQUEST=GetFeature&SERVICE=WFS&version=2.0.0&TYPENAMES=cp:CadastralParcel&RESOURCEID=cadastralparcel.2

returns the exception.

**Comment by cportele** [comment]
cc @azahnen

**Comment by cportele** [comment]
I have switched the service off and close the issue. I don't think the situation will change during the hackathon.
